---
name: generate-changelog

on:
  pull_request:
    types: [opened]
    branches: ["main", "main-*"]

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Changelog
        if: contains(github.event.pull_request.labels.*.name, 'kind/release')
        uses: saadmk11/changelog-ci@v1.0.0
        with:
          config_file: "changelog-ci.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
